using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.16209.2248")]
[assembly: AssemblyFileVersionAttribute("1.0.16209.2248")]
[assembly: AssemblyCopyrightAttribute("Copyright © CRIneta 1979-2009")]
[assembly: AssemblyProductAttribute("CRIneta")]
[assembly: AssemblyCompanyAttribute("CRIneta")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyInformationalVersionAttribute("1.0.16209.2248")]

