using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.16409.0853")]
[assembly: AssemblyFileVersionAttribute("1.0.16409.0853")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003-2009 CRineta")]
[assembly: AssemblyProductAttribute("CRineta")]
[assembly: AssemblyCompanyAttribute("CRineta")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyInformationalVersionAttribute("1.0.16409.0853")]

