using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("1.0.27809.1817")]
[assembly: AssemblyFileVersionAttribute("1.0.27809.1817")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003-2009 Groop")]
[assembly: AssemblyProductAttribute("Groop")]
[assembly: AssemblyCompanyAttribute("Groop")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyInformationalVersionAttribute("1.0.27809.1817")]

